int [] rew = new int [5];
rew[0] = 5;
rew[1] = 23;
rew[2] = 67;
rew[3] = 99;
rew[4] = 7;
Console.WriteLine(rew[0]);
Console.WriteLine(rew[1]);
Console.WriteLine(rew[2]);
Console.WriteLine(rew[3]);
Console.WriteLine(rew[4]);